# Generated by Django 5.2.4 on 2025-07-26 01:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resena',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Reseña'),
        ),
    ]
